fauna/faunadb-python

faunadb/objects.py
tests/objects_test.py

* Dont' use `json` as a variable name; people will think this means a string.
* Add mappers to Page.set_iterator

Improve objects

---

build.py
faunadb/query.py
tests/query_test.py

concatWithSeparator, modulo, and, or, not, prepend, append

Added new queries

---

faunadb/_json.py
faunadb/client.py
faunadb/errors.py
faunadb/objects.py
faunadb/query.py
tests/client_test.py
tests/errors_test.py
tests/objects_test.py
tests/query_test.py
tests/test_case.py

Has a few TODOs before we can merge, but ready to review.

Revise errors.py and add ErrorData classes.

---

faunadb/query.py
tests/objects_test.py
tests/query_test.py

Query updates

---

.gitignore
Makefile
README.rst
setup.py

Support for running tests from setup.py

---

faunadb/errors.py
tests/helpers.py
tests/test_client.py
tests/test_errors.py
tests/test_query.py

Remove 'HTTP' from FaunaError names

---

tests/helpers.py
tests/test_errors.py

Had to write our own `assert_raises` because `self.assertRaises` won't return a value.

Use assert_raises when capturing exceptions

---

tests/helpers.py
tests/test_client.py
tests/test_errors.py
tests/test_objects.py
tests/test_query.py

Should provide better error messages when asserts fail.

Switch to unittest asserts

---

.coveragerc
.coveralls.yml
.gitignore
.travis.yml
Makefile
setup.py

Add Coveralls for test coverage

---

faunadb/errors.py
faunadb/objects.py
tests/test_client.py
tests/test_client_logger.py
tests/test_errors.py
tests/test_objects.py
tests/test_page.py
tests/test_query.py

Should wait on #80 and probably #81

Improve test coverage

---

.travis.yml
codecov.yml

closes https://github.com/faunadb/sales-engineering/issues/394

setup codecov

---

faunadb/_json.py
faunadb/client.py
faunadb/errors.py
faunadb/query.py
tests/helpers.py
tests/test_errors.py
tests/test_query.py

fix some pylint errors and increase code coverage

Pylint and coverage

---

README.rst

switch to shields.io to render codecov badges and fix badges target rendering

shields.io badges

---

CHANGELOG.md
README.rst
faunadb/__init__.py

closes https://github.com/faunadb/sales-engineering/issues/412

Release 0.1.0

---

CHANGELOG.md
faunadb/query.py
tests/test_query.py

Part of https://github.com/faunadb/sales-engineering/issues/435
Closes https://github.com/faunadb/sales-engineering/issues/494

Add key_from_secret function

---

CHANGELOG.md
faunadb/query.py
tests/test_query.py
tests/test_serialization.py

Part of https://github.com/faunadb/sales-engineering/issues/513.
Fixes https://github.com/faunadb/sales-engineering/issues/518.

Add at function support

---

tests/test_client.py

We are trying to test that ping works in the driver, not that every node in the cluster is up.

Ping at node, not all

---

.gitignore
faunadb/_json.py
faunadb/objects.py
faunadb/query.py
tests/test_deserialization.py
tests/test_query.py
tests/test_serialization.py

this PR implements `@query` types along with some lint warnings fixes

DRIV-3 Adds support for @query type (user defined functions)

---

CHANGELOG.md
faunadb/__init__.py

Prep for releasing the driver as version 1.1.0

New release

---

Makefile
faunadb/deprecated.py
faunadb/page.py
faunadb/query.py
tests/test_errors.py
tests/test_objects.py
tests/test_query.py
tests/test_serialization.py

This PR is the result of the last review on recursive references

Deprecate *_expr() functions

---

.dockerignore
Dockerfile.test
Makefile
README.rst

Working in Jenkins just fine right now.

CI-12: Add dockerfile for running tests in CI

---

CHANGELOG.md
faunadb/query.py
tests/test_client_logger.py
tests/test_query.py
tests/test_serialization.py

this pr includes
* `abort` function
* `casefold:` with `normalizer` parameter
* deprecate `next_id` function
* `new_id` function
* `singleton` function
* `events` function
* `identity` function
* `has_identity` function

Adds missing functions

---

CHANGELOG.md
faunadb/__init__.py

- Added `documents`, `now`
- Added `any` , `all`
- Added `count`, `sum`, `mean`
- Added `time_add`, `time_subtract`, `time_diff`
- Added `starts_with`, `ends_with`, `contains_str`, `contains_str_regex`, `regex_escape`
- Updated references to documentation

Release v2.11.0

---

.travis.yml
README.rst

Add python 3.7 to CI

---

CHANGELOG.md
faunadb/__init__.py

- Added client specified query timeout
- Added Python 3.7 and 3.8 to CI

Release v2.12.0

---

faunadb/client.py
faunadb/query.py
tests/test_query.py
tests/test_serialization.py

- Adds contains_path, contains_value, contains_field, deprecates contains

DRV-188: Refactor contains into family of functions

---

faunadb/query.py
tests/test_query.py
tests/test_serialization.py

DRV-104: Add reverse()

---

CHANGELOG.md
README.rst
faunadb/__init__.py

- Refactored `contains` into `contains_path`, `contains_value`, `contains_path`
- Added `reverse` function
- Bump api version to `3`
- Add tests for versioned lambdas

Release v3.0.0

---

.circleci/config.yml
tests/test_errors.py
tests/test_query.py

- Followup PR to update failing tests once this is merged
- Added Python 2.7, 3.4 and 3.8

Add circleci config

---

faunadb/query.py
tests/test_query.py
tests/test_serialization.py

- Adds is_*type* family of functions.

DRV-270: Add missing type check functions

---

faunadb/__init__.py
faunadb/client.py
tests/test_client.py

The driver needs a new header to track the runtime environment.
Python version
Driver version
Operating system
Cloud provider
[DRV-517](https://faunadb.atlassian.net/browse/DRV-517)

DRV-517 runtime headers

---

CHANGELOG.md
faunadb/__init__.py

Release version 4.1.0

---

tools/loadTest.py

[OSS-674 Parallel testing](https://faunadb.atlassian.net/browse/OSS-674)

feature: load test

---

faunadb/__init__.py

[Notify users via command line when driver has been updated](https://faunadb.atlassian.net/browse/OSS-663)

feature(OSS-663): notify users about new version

---

.circleci/config.yml
faunadb/client.py
faunadb/streams/client.py
faunadb/streams/events.py
tests/test_streams.py

Changes: 
* New event type;
* New event handler callback;
* New valid field;
* Test cases.

ENG-3044: Introduce support for set streaming

---

.circleci/config.yml
.github/workflows/create-jira-ticket-on-issue.yml
faunadb/client.py
faunadb/streams/client.py
faunadb/streams/events.py
tests/test_streams.py

This reverts commit 2790c3c6330b8da1c360976faa7bce570de0c352, reversing
changes made to 42acb1b31e7f7cfe6153ac8ef77a3d82e64679ea.
Fat fingered the merge early.

Revert "Merge branch 'main' into v4"
