- faunadb/query.py
`varargs_query` was unnecessarily complicated and wouldn't work for
functions that had other arguments in addition to the rest arg.
> Cleanup handling of varargs

- faunadb/client.py
- tests/helpers.py
- tests/test_client.py
- tests/test_client_logger.py
- tests/test_errors.py
- tests/test_query.py
closes https://github.com/faunadb/sales-engineering/issues/353
> adds new_session_client method

- tests/test_errors.py
Aka "I wanted to run this to run under IntelliJ and it was incorrectly failing".
> Fix up test_json_serialization to work under alternate runners

- CHANGELOG.md
- faunadb/_json.py
- tests/test_deserialization.py
- tests/test_serialization.py
I'm not sure how I feel about this, but this is an implementation of `@bytes` support for Python without using a wrapper. In Python 2.x, objects of the type `bytearray` are encoded as `@bytes` and are then decoded as `bytearray`. In Python 3.x, objects of the type `bytes` or `bytearray` are encoded as `@bytes`, and are then decoded as `bytes`.
Part of https://github.com/faunadb/sales-engineering/issues/436.
Fixes https://github.com/faunadb/sales-engineering/issues/509.
> Support for @bytes type

- README.rst
I used the simple example from jvm driver
close https://github.com/fauna/faunadb-python/issues/112
> Adds basic usage example

- faunadb/client.py
- tests/test_client.py
Previously, the client did not send or track the last transaction timestamp.  This patch adds that piece of state hanging off the client class.
Not really a Python person so not sure how idiomatic this is, so feel free to pick apart as you see fit.
> ENG-146: send X-Last-Seen-Txn by default

- faunadb/client.py
Error:
```bash
In [4]: client = FaunaClient(secret="**********",domain="localhost",scheme="http",port=8443)
In [5]: 
In [5]: client.query(q.paginate(q.indexes()))
---------------------------------------------------------------------------
BadRequest                                Traceback (most recent call last)
<ipython-input-5-a0296a89aeb8> in <module>()
----> 1 client.query(q.paginate(q.indexes()))
/home/*/git/faunadb-python/faunadb/client.pyc in query(self, expression, timeout_millis)
185     :return: Converted JSON response.
186     """
--> 187     return self._execute("POST", "", _wrap(expression), with_txn_time=True, query_timeout_ms=timeout_millis)
188 
189   def ping(self, scope=None, timeout=None):
/home/*/git/faunadb-python/faunadb/client.pyc in _execute(self, action, path, …
```
> DRV-88: Fix None query timeout on FaunaClient constructor

- faunadb/client.py
- faunadb/objects.py
- faunadb/query.py
- tests/test_3rdpartyauth.py
- tests/test_query.py
- tests/test_serialization.py
- Adds access_provider functions. (create_access_provider, access_provider, access_providers )
- Deprecates identity() in favor of current_identity()
- Deprecates has_identity() in favor of has_current_identity()
- Adds has_current_token() and current_token() functions 
- Added 3rdparty_auth test suite
- Bumps api_version to 4
https://faunadb.atlassian.net/browse/DRV-275
> Add third party auth functions.

- faunadb/client.py
- faunadb/streams/__init__.py
- faunadb/streams/client.py
- faunadb/streams/dispatcher.py
- faunadb/streams/errors.py
- faunadb/streams/events.py
- faunadb/streams/subscription.py
- setup.py
- tests/test_query.py
- tests/test_streams.py
Introduces the streaming api for the Python driver.
Notable changes and limitations.
- For backwards compatibility, using asyncio was not implemented. However most of our users report using Python 3.4+ so this will likely be implemented in the near future. Related: #161
-  Started stream subscriptions are blocking by default. If started asynchronously by passing `blocking=False` to the FaunaClient stream method, the event loop will be started in a separate thread.
- Currently each stream has its own HTTP/2 connection(separate from the FaunaClient connection). A connection pool for stream connections and/or using the HTTP/2 adapter for the FaunaClient are necessary to effectively utilize HTTP/2 multiplexing for streams.
- Python 3.6+ deprecations with hyper. To support HTTP/2 we use hyper, …
> DRV-302: Introduce streaming api

- README.rst
> Document streaming api in README

- CHANGELOG.md
- faunadb/__init__.py
- Introduce document streaming api
- Add third party auth functions
- Bump api_version to `4`
- Add nightly and stable CI for Python 2.7, 3.4 and 3.8
> Release v4.0.0

- README.rst
- faunadb/client.py
- faunadb/streams/client.py
**Issue**
Support for `create_access_provider` and related functions has been implemented, but the lack of Bearer token support means that Python-based client applications cannot succeed in using JWT tokens in place of secrets: they always receive the error `Unauthorized`.
**Ho to test?**
follow [instruction](https://docs.fauna.com/fauna/current/security/external/auth0) to obtain an access token
```
from faunadb import query as q
from faunadb.client import FaunaClient
from faunadb.objects import Ref
client = FaunaClient(
secret='place jwt here',
)
print(client.query(q.paginate(q.documents(q.collection('users')))))
def on_start(event):
print("started stream at %s"%(event.txn))
def on_version(event):
print("on_version event at %s"%(event.txn))
print("    event: %s"%(event.event)) …
```
> DRV-398 Support Bearer auth tokens

- faunadb/client.py
- tests/test_client.py
Rework runtime env header format. Current format
`driver=python-4.0.1; runtime=python-3.7.7-final env=gcp compute instances; os=darwin-18.7.0`
> feature(client.py): rework runtime env header

- faunadb/query.py
- tests/test_query.py
In the python driver, Select() does not accept the 3rd default parameter.
It would be better if we didn't have to use select_with_default() - as this isn't very intuitive and not according to the Docs.
[DRV-525](https://faunadb.atlassian.net/browse/DRV-525)
> DRV-525 select with default

- faunadb/query.py
- tests/test_query.py
Implement the [sentinel object pattern](https://python-patterns.guide/python/sentinel-object/#sentinel-objects) to distinguish explicit passing of `None` for `default`
Fixes #191
> Allow None as value to select's default parameter

- faunadb/client.py
- faunadb/errors.py
- tests/test_client.py
- tests/test_errors.py
[Shallow ValidationError - Expose "failures" object](https://faunadb.atlassian.net/browse/OSS-578)
If you create a collection or index, immediately delete it, and then try creating either, it throws a BadRequest saying document data is invalid without details of the real error cause.
```python
from faunadb import query as q
from faunadb.client import FaunaClient
client = FaunaClient(secret="")
client.query(q.create_collection({"name": "test"}))
client.query(q.delete(q.collection('test')))
client.query(q.create_collection({"name": "test"}))
```
before
```
faunadb.errors.BadRequest: document data is not valid.
```
after
```
faunadb.errors.BadRequest: ErrorData(code='validation failed', description='document data is not valid.', position=['create_collection'], …
```
> fix(OSS-578): expose whole error

- faunadb/client.py
- tests/test_client.py
We should make sure that the `x-query-timeout` header is always sent to the server with either the user-defined query timeout, or with the client-side request timeout.
[DRV-522](https://faunadb.atlassian.net/browse/DRV-522)
> feature!: always pass X-Query-Timeout

- README.rst
Concourse CI creates a separate folder in the `gh-pages` for a specific version, this PR adds a reference to the latest `v4` version of the driver into the readme file.
> chore(FE-1639): Changed reference to a docs for particular version

- faunadb/query.py
FQL functions don't have underscores in their names, even though that's the convention we used for Python driver implementations.
> OSS-991: Fix bad documentation links

- .github/workflows/close-jira-ticket.yml
- .github/workflows/create-jira-ticket-on-issue.yml
Our Atlassian references were referring to `main` branches that Atlassian does not have.
Updated to refer to `master` which they do have.
> Update atlassian references to master branch not main - as atlassian has no 'main' branches - just 'master'
